# Generated by Django 4.2.1 on 2023-06-16 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0006_merge_20230601_1829'),
        ('prescriptions', '0009_remove_prescriptions_personnes'),
    ]

    operations = [
    ]
