# Generated by Django 4.2.1 on 2023-06-16 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0010_merge_20230616_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescriptions',
            name='personnes',
        ),
    ]
